# Generated by Django 5.0.7 on 2024-07-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactus_sportcategory_equipment_feedback_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'CustomPluralName'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'CustomPluralName'},
        ),
    ]
